// src/components/portifolio/clients-list/clients-list.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-clients-list',
  templateUrl: './clients-list.component.html',
  styleUrls: ['./clients-list.component.css']
})
export class ClientsListComponent {

}

<div class="container">
    <div class="cards-container">
      <ul class="cards_list">
        <li class="card">
          <img src="/assets/portfolioImages/bny.png" alt="Minha Imagem Estilizada" class="styled-image">
        </li>
        <li class="card">
          <img src="/assets/portfolioImages/firjan.png" alt="Minha Imagem Estilizada" class="styled-image">
        </li>
        <li class="card">
          <img src="/assets/portfolioImages/muvz.png" alt="Minha Imagem Estilizada" class="styled-image">
        </li>
        <li class="card">
          <img src="/assets/portfolioImages/stefanini.png" alt="Minha Imagem Estilizada" class="styled-image">
        </li>
        <li class="card">
          <img src="/assets/portfolioImages/pjerj.png" alt="Minha Imagem Estilizada" class="styled-image">
        </li>
      </ul>
    </div>
  </div>

// src/components/portfolio/clientsList/clientsList.tsx
import React from 'react'
import * as S from './styles'
import Image from 'next/image'

export const ClientsList = () => {
    return (
        <S.Container>
            <S.CardsContainer>
                <S.Card>               
                    <S.StyledImage src='/assets/imagesPortfolio/bny.png' alt="Minha Imagem Estilizada" />
                </S.Card>
                <S.Card>               
                    <S.StyledImage src='/assets/imagesPortfolio/firjan.png' alt="Minha Imagem Estilizada" />
                </S.Card>
                <S.Card>               
                    <S.StyledImage src='/assets/imagesPortfolio/muvz.png' alt="Minha Imagem Estilizada" />
                </S.Card>
                <S.Card>               
                    <S.StyledImage src='/assets/imagesPortfolio/stefanini.png' alt="Minha Imagem Estilizada" />
                </S.Card>
                <S.Card>               
                    <S.StyledImage src='/assets/imagesPortfolio/pjerj.png' alt="Minha Imagem Estilizada" />
                </S.Card>
            </S.CardsContainer>
        </S.Container>
    )
}

    export default ClientsList;
