// src/components/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent {
  constructor() { }

  ngOnint(): void {
    
  }
}

<footer>
    <div class="footer-content">
      <h1>Lucas Technology Services</h1>
      <h3>All rights reserved</h3>
      <a href="https://github.com/LesterCerioli"><img src="./assets/navBar/logotipo-do-github.png" alt="Logo Github"></a>
      <a href="https://www.linkedin.com/company/71696971/admin/feed/posts/"><img src="./assets/navBar/logotipo-do-linkedin.png" alt="Logo Linkedin"></a>
    </div>
  </footer>

// src/components/shared/footer/footer.tsx
"use client"
import * as S from "./styles";

export function Footer() {
    return (
        <S.Container>
            <S.SpanContainer>
                <S.Brand>Lucas Technology Services</S.Brand>
                <S.Copyright>All rights reserved</S.Copyright>
            </S.SpanContainer>
            <S.SocialsContainer>
                <S.Socials href="https://www.linkedin.com/company/71696971/admin/" target="_blank">
                    <S.LinkedinIcon className="linkedin-icon" />
                </S.Socials>
                <S.Socials href="https://github.com/Lucas-Technology-Services" target="_blank">
                    <S.GithubIcon className="github-icon" />
                </S.Socials>
            </S.SocialsContainer>
        </S.Container>
    )
}
