// src/components/portfolio/ourGithub/ourGithub.tsx
import React from 'react'
import * as S from './styles'
import Image from 'next/image';

export const OurGithub = () => {
    return (
      <S.Container>
        <div>
          <S.Title>Visit our Github</S.Title>
          <S.SpanDiv>
            <S.Span />
          </S.SpanDiv>
        </div>
        <S.RepositoryContainer>
          <div>
            <Image src='/assets/imagesPortfolio/github.png' alt='Github logo' width={375} height={210} />
          </div>
          <S.GithubContainer>
            <S.Subtitle>Our Repository</S.Subtitle>
              <a href='https://github.com/Lucas-Technology-Services' target="_blank">
                <S.Button>Our Github</S.Button>
              </a>
          </S.GithubContainer>
        </S.RepositoryContainer>
      </S.Container>
    );
  };

  export default OurGithub;

// src/components/portifolio/our-github/our-github.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-our-github',
  templateUrl: './our-github.component.html',
  styleUrls: ['./our-github.component.css']
})
export class OurGithubComponent {

}

<div class="container">
    <div>
      <h1 class="title">Visite nosso Github</h1>
      <div class="span-div">
        <span class="span"></span>
      </div>
    </div>
    <section class="repository-container">
      <div>
        <img src="/assets/portfolioImages/github.png" alt="Github logo" class="github-image">
      </div>
      <div class="github-container">
        <h6 class="subtitle">Nosso repositório</h6>
        <a href="https://github.com/Lucas-Technology-Services" target="_blank">
          <button class="github-button">Nosso Github</button>
        </a>
      </div>
    </section>
  </div>
